### ISSUE TITLE
db용 요구사항

### ISSUE THREAD

**Issue by neocjmix** [NHNNEXT/2015-01-HUDIWEB-MARCH4#16]

**Comment by helloheesu** [comment]
[db용 기능 세부정의](https://github.com/NHNNEXT/2015-01-HUDIWEB-MARCH4/wiki/db-%EA%B0%9D%EC%B2%B4-%EC%84%A4%EA%B3%84%EB%A5%BC-%EC%9C%84%ED%95%9C-%EA%B8%B0%EB%8A%A5-%EC%84%B8%EB%B6%80%EC%A0%95%EC%9D%98)
